### ISSUE TITLE
20/01 Add ECR use instructions

### ISSUE THREAD

**Issue by rsanz** [Ingenia-SE/TDF-SARUS#1]
<img src="https://raw.githubusercontent.com/Ingenia-SE/TDF-SARUS/main/img/logo-color.png?raw=true" alt="TDF-Logo" width="210">

| Project: | SARUS | ECR ID#: | 20/01 |
|---------:|---------|----------:|--------|
| **Requestor:** | Ricardo Sanz | **Date:** | 14/11/2020 |
| **Project Managers:** | Diego Cerrillo / Lucía Honrubia | **Priority:** | Priority level |
| **Configuration Managers:** | Antonio Márquez / Luis Saz | **CI Target:** | Target |

**Change request type:** 
- [ ] New Requirement
- [ ] Requirement Change
- [ X] Other

**ECR Classification:** 
- [ ] Major
- [ C] Minor

**Requested change description:** give a description about the request you're about to submit.

Add info on how to use the ECR/issue in the repo README.md. A SysML activity diagram would be nice.

**Requested change reason:** argument why this should be taken account of.

This will help unify workflows and have a well understood process.

**Comment by amarqz** [comment]
Thanks for the suggestion! We'll consider its addition.

Time and date recorded: 14:35 on Saturday, Nov. 14.

**Comment by amarqz** [comment]
The suggested change has been approved and partially implemented.
An explanation has been added in the README.md file. In the future, a SysML activity diagram will be incorporated to it.

Time and date closed: 16:23 on Saturday, Nov. 14.
