### ISSUE TITLE
20/02 Correct logo path in ECR

### ISSUE THREAD

**Issue by rsanz** [Ingenia-SE/TDF-SARUS#2]
<img src="https://raw.githubusercontent.com/Ingenia-SE/TDF-SARUS/main/img/logo-color.png?raw=true" alt="TDF-Logo" width="210">

| Project: | SARUS | ECR ID#: | yy/nn |
|---------:|---------|----------:|--------|
| **Requestor:** | Ricardo Sanz | **Date:** | 14/11/2020 |
| **Project Managers:** | Diego Cerrillo / Lucía Honrubia | **Priority:** | Priority level |
| **Configuration Managers:** | Antonio Márquez / Luis Saz | **CI Target:** | Target |

**Change request type:** 
- [ ] New Requirement
- [ ] Requirement Change
- [x] Other

**ECR Classification:** 
- [ ] Major
- [x] Minor

**Requested change description:** give a description about the request you're about to submit.

The current ECR template contains this path to the logo:

https://github.com/amarqz/amarqz/blob/main/TDF/logo-color-noname.png

<img src="https://github.com/amarqz/amarqz/blob/main/TDF/logo-color-noname.png?raw=true" alt="TDF-Logo" width="60">

Is is better to use one in the same repository, e.g.:

https://raw.githubusercontent.com/Ingenia-SE/TDF-SARUS/main/img/logo-color.png

<img src="https://raw.githubusercontent.com/Ingenia-SE/TDF-SARUS/main/img/logo-color.png?raw=true" alt="TDF-Logo" width="60">

**Requested change reason:** argument why this should be taken account of.

The current logo path is not working.

**Comment by amarqz** [comment]
Thanks for reporting the bug! We'll fix it as soon as possible.

Time and date recorded: 14:31 on Saturday, Nov. 14.

**Comment by amarqz** [comment]
The reported bug has been fixed.

Time and date closed: 16:32 on Saturday, Nov. 14.
