### ISSUE TITLE
21/01 Change to IBM Rhapsody

### ISSUE THREAD

**Issue by dcerrillov** [Ingenia-SE/TDF-SARUS#3]
<img src="https://raw.githubusercontent.com/Ingenia-SE/TDF-SARUS/main/img/logo-color.png" alt="TDF-Logo" width="210">

| Project: | SARUS | ECR ID#: | 21/01|
|---------:|---------|----------:|--------|
| **Requestor:** | Diego Cerrillo Vacas | **Date:** | 12/01/2021|
| **Project Managers:** | Diego Cerrillo / Lucía Honrubia | **Priority:** | High |
| **Configuration Managers:** | Antonio Márquez / Luis Saz | **CI Target:** | Target |

**Change request type:** 
- [ ] New Requirement
- [ ] Requirement Change
- [X] Other

**ECR Classification:** 
- [ ] Major
- [x] Minor

**Requested change description:** Changing program from Papyrus to IBM Rhapsody

**Requested change reason:** We have already spent time trying to solve some bugs and issues when changing computers (after someone uploads the model to github) due to style. Much time will be saved if changed before we start the actual model in SYSML.

**Comment by amarqz** [comment]
Thanks for the suggestion! We'll consider it.

Time and date recorded: 18:33 on Wednesday, Jan. 13.

**Comment by amarqz** [comment]
After discussing, the change proposal has been accepted and it will be implemented. IBM Rhapsody licences will be delivered to our team members and models will be done in it.

Time and date closed: 18:38 on Wednesday, Jan. 13.
